import React from 'react';

const Main = () => {
	return (
		<main className='main'>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis unde esse repellendus, dolores repudiandae fuga possimus ex consectetur maxime nobis ipsam, ab velit aperiam sint explicabo debitis! Voluptatibus, id hic.
		Aperiam modi reiciendis fugiat officia blanditiis accusantium expedita cupiditate voluptatibus tempora possimus tenetur ullam aliquid, facilis animi ex cumque perspiciatis illo obcaecati assumenda. Ut debitis hic nulla, incidunt velit ad.
		Iste tenetur impedit, alias reiciendis nemo laudantium illo aut! Corrupti omnis delectus architecto natus quidem, totam veniam soluta, ut nobis vero provident ipsa sint praesentium eligendi earum culpa odio cumque.
		Culpa placeat laudantium quisquam accusamus distinctio debitis minima voluptate, quos amet maxime excepturi repellendus quaerat earum obcaecati molestias porro! Doloremque hic perferendis voluptatem corrupti nobis animi quis fuga enim officiis?
		Sint adipisci ullam nesciunt sit nobis numquam, minima possimus voluptatum dolores incidunt facere at iusto laboriosam cum ratione voluptas quae. Saepe eligendi itaque officia tempora sapiente adipisci a laboriosam ab!
		Officiis temporibus quaerat facilis voluptates sed culpa ex animi vero nihil? Consectetur consequatur labore numquam blanditiis quibusdam porro autem, ea amet ad, deserunt minima dolorem rem inventore. Quasi, quisquam accusantium.
		Pariatur architecto voluptate animi temporibus veniam, modi quae sit blanditiis a quis quaerat alias at quam repellat quas totam, officia quos incidunt eligendi voluptatem cumque. Saepe facere aliquid corrupti atque.
		Optio hic eveniet id nesciunt ratione aperiam minus repellat explicabo esse dolor pariatur delectus modi itaque consequuntur quas, labore deleniti voluptatem at facere! Animi inventore voluptates sint velit vero aspernatur.
		Molestiae, asperiores temporibus autem quibusdam delectus amet perferendis? Rerum reiciendis voluptas porro cum praesentium quia. Veniam at a natus error rerum, reprehenderit quasi asperiores est provident perferendis quidem! Totam, facere!
		Optio ducimus ex ratione eaque, reiciendis animi dicta nisi! Tempora facere reprehenderit delectus quis possimus sapiente odio? Odit mollitia at veritatis non, reprehenderit, recusandae debitis nisi error minima aut qui?
		Quis non aperiam atque suscipit velit accusamus maiores praesentium mollitia rem, quo, laborum porro deserunt nesciunt! Commodi rerum, nesciunt similique laudantium sed explicabo sapiente quis nemo quidem. Vitae, cum laborum.
		Sequi doloribus libero dignissimos necessitatibus similique voluptatem eligendi magnam quos officia porro deserunt excepturi, ab et nesciunt ullam animi id voluptatibus. Suscipit adipisci repellendus ipsa voluptate quas harum provident aperiam.
		Quisquam aliquam est neque itaque. Accusantium consequuntur iusto aliquid minus consequatur, velit maiores quasi vero itaque placeat maxime! Rerum consectetur corrupti expedita non animi sit enim totam, accusantium ipsam molestiae!
		Molestias, recusandae obcaecati quia quibusdam minus sapiente quo officia molestiae. Id fugiat perferendis aperiam ex adipisci inventore, facere ducimus. Consequuntur magni cumque ea labore amet earum ipsam perspiciatis qui mollitia!
		Pariatur corporis fuga modi illo rem sapiente quisquam mollitia quae odio, ex necessitatibus placeat quia impedit ducimus autem veritatis fugit nam iusto nemo animi eum vel exercitationem itaque. Ea, ducimus?
		Neque sint, quam perspiciatis quo corrupti numquam cum, recusandae quod incidunt consequuntur, deserunt nesciunt eos laborum molestias quibusdam. Neque similique, voluptatum vitae quo deserunt aliquid distinctio. Voluptatibus eligendi vitae id.
		Nemo magnam tempore sunt ipsum enim eos aliquam libero? Veniam, minus quia. Qui id, quas obcaecati repellendus ullam quasi asperiores inventore temporibus odit cupiditate provident explicabo sint nobis nesciunt dicta.
		Adipisci ducimus consequatur minus dolorem amet reiciendis eos dolorum, unde in totam assumenda repellendus error magni dolores quam laboriosam illum! Error possimus dolor saepe, expedita ut harum laborum iste quo!
		Consequuntur qui architecto incidunt, delectus ex sint, ipsum tempora placeat quia eligendi id tempore quasi accusamus sunt dolore at. Sit asperiores repellendus deleniti expedita consequuntur ea? Incidunt voluptatibus ipsa labore!
		A libero beatae incidunt dignissimos adipisci quam ullam officiis maiores consequatur! Asperiores doloremque adipisci consequuntur veniam rem provident saepe. Quasi repudiandae cumque libero nulla odio aliquid quis enim, nisi maiores?
		Suscipit aperiam accusantium, distinctio perspiciatis quos, reprehenderit itaque, aliquam nobis possimus autem exercitationem. Labore maxime, nihil atque reprehenderit distinctio praesentium tempora quidem autem eligendi, consequuntur libero veritatis incidunt neque illo?
		Error ipsa labore, quibusdam quae earum voluptatum facilis reprehenderit ipsum. Ex odio molestias repellendus esse repudiandae expedita nam alias odit nihil ipsa consequuntur eligendi rerum obcaecati, cumque perspiciatis, aperiam earum!
		Aliquam maiores, nihil perspiciatis nostrum saepe quae veniam aperiam sequi atque voluptatibus officiis expedita magnam optio molestiae inventore rerum quod eius possimus, doloribus corporis eaque veritatis assumenda ab laboriosam! Quasi.
		Quibusdam repellat illo quae? Explicabo quam aliquam consectetur autem aspernatur obcaecati eligendi non officia a maiores distinctio quia neque vel suscipit repellat iste ut reprehenderit, eveniet libero qui. Maiores, nostrum.
		Libero accusamus at aliquam unde explicabo ut facere atque consequuntur, ab magnam repellendus error! Aliquam, perferendis. Quis asperiores sunt perspiciatis fugit ab dicta fugiat soluta eligendi aspernatur. Dignissimos, consequuntur molestiae.
		Ipsam alias necessitatibus, dolorem perspiciatis asperiores aperiam earum amet similique adipisci fuga molestias distinctio culpa explicabo, dolorum at accusamus, impedit obcaecati. Facere sequi quidem consequuntur temporibus voluptas nostrum, et autem?
		Est, hic corrupti consectetur debitis dolore consequatur qui ipsum, totam nulla reprehenderit deserunt voluptate expedita eveniet! Laborum quo architecto adipisci magnam totam, aut, voluptate reiciendis at, alias non ducimus molestiae.
		Assumenda asperiores autem, repellendus aliquid magni impedit! Sequi ipsum ut sit saepe voluptates provident asperiores et itaque pariatur dolores. Ipsum ab, aliquam porro officia ipsam consectetur id eos accusamus obcaecati!
		Doloremque aspernatur assumenda accusamus animi rerum provident quas temporibus perferendis hic delectus facere, consectetur reprehenderit repellendus dolores facilis illum aperiam deserunt iure atque nesciunt magnam esse, quasi consequuntur sunt! Eligendi!
		Eum asperiores veniam voluptatem dolore, quae vel ea atque vitae, placeat deserunt, sequi iure velit ducimus eveniet quidem non rem veritatis accusantium assumenda iusto. Perspiciatis accusamus magni repellat facere est!
		Earum iste quos aspernatur, deleniti exercitationem sit at sed suscipit? Alias nulla eaque iusto est, sunt dignissimos voluptates! Quaerat rem doloremque adipisci reprehenderit sit cumque aliquid, repellat esse velit animi?
		Distinctio ut harum dolores minima iure ratione excepturi quae nesciunt earum quaerat cupiditate aliquam vitae, ab iusto quibusdam reiciendis corrupti fuga vero. Dignissimos id fuga enim vitae labore fugiat. Quaerat.
		Eaque hic sapiente, recusandae corrupti voluptate eum laudantium beatae, sunt quidem vero commodi at. Excepturi, vero velit itaque consequuntur exercitationem ipsam sunt reprehenderit voluptates, architecto maxime beatae eum laudantium dicta.
		Dolorem, asperiores minima delectus fugiat amet non error a aspernatur quisquam molestias ullam dolores fugit, facere numquam quia architecto ipsum, velit aperiam harum earum vero veritatis dicta deleniti. Sapiente, explicabo?
		Ducimus voluptas, cupiditate aut in quia voluptatum obcaecati consequatur ratione placeat, reiciendis sequi minus ea deleniti dicta. Quis repellat reprehenderit a atque unde assumenda dolor eveniet, odio iste, autem impedit.
		Ullam tempora molestiae tenetur culpa fugit nostrum minus quis inventore voluptatem excepturi ratione, suscipit at perspiciatis porro fugiat eligendi, impedit ipsum architecto quasi rerum laborum eveniet. Expedita earum nobis ullam.
		Voluptatibus necessitatibus quod, vel sapiente, nam voluptatem dolores esse optio sequi laudantium ab quaerat non dolor veniam, iusto deleniti voluptate eius. A, quasi suscipit! Recusandae architecto debitis accusamus voluptatibus quia?
		Sit, facere odit. A minus dolorem nihil exercitationem dicta, architecto dolor, voluptate quasi pariatur mollitia tempore voluptatum nisi ab perspiciatis necessitatibus ex, rem explicabo fuga sit esse nam! Aut, quos?
		Accusantium velit sequi laborum adipisci unde aut placeat veritatis, repellat modi ex doloribus mollitia! Consequuntur ratione vel earum facilis sed assumenda, alias sit suscipit inventore voluptatem harum? Vitae, et sunt!
		At harum reprehenderit consectetur asperiores. Minima quibusdam dolore sed similique quasi explicabo tempora exercitationem, eos nostrum ducimus iusto quae adipisci iure, et eligendi repellat eaque ullam error omnis praesentium nobis.
		Ex tenetur accusantium voluptas ipsum possimus corporis nihil vel quia quo eligendi, rem officia incidunt illo vitae aspernatur similique reiciendis minus. Fugiat ipsa pariatur iusto est cum itaque suscipit ut?
		Et reiciendis recusandae ex rerum eum? Ullam recusandae, tenetur quo molestiae unde expedita, accusantium, consequuntur nam perspiciatis deleniti dolor. Ea fugit iusto iste, accusamus sit error! Sequi animi quo veniam!
		Exercitationem ratione minima veritatis, quae quod ut voluptatibus rerum aperiam ipsa eveniet ea blanditiis assumenda vero, aliquam impedit molestiae sequi accusantium quisquam nobis aliquid, unde est. Repellat, facere! Saepe, vitae.
		Optio natus, quidem adipisci eligendi facilis rem nostrum vitae excepturi iusto aut repellat officia, corrupti eos delectus et? Exercitationem hic repudiandae, maxime laboriosam perferendis id? Incidunt necessitatibus natus quo neque.
		Hic vitae eum, ipsum nesciunt cupiditate maxime. Voluptatem voluptate nostrum sequi hic recusandae quaerat perferendis, aliquam eaque soluta dolore qui consectetur molestias maxime illum iste, optio fugiat quasi ad laborum!
		Id, consectetur placeat fugiat, iure, inventore veritatis at velit aut molestias ducimus dolorem. Voluptates veritatis rem obcaecati consequatur voluptas vel laboriosam voluptatibus quos nostrum reprehenderit? Nesciunt non quis debitis numquam!
		Aliquam atque harum eius non laudantium minus error repudiandae, sit aut, excepturi similique tempore? Ad rem sed atque alias corrupti voluptates, laborum iste quae, quis ipsa odio libero cum eligendi!
		Accusantium sit corporis amet, temporibus eligendi mollitia molestias eos. Praesentium consequatur nam iste, dolore animi sit cupiditate? Id iste laboriosam totam quis ipsam, sequi debitis recusandae harum ipsa! Deserunt, quidem?
		Nulla aspernatur itaque deleniti distinctio laudantium magnam modi vitae quis delectus cupiditate porro perspiciatis quod culpa vel facere odio aut ad perferendis alias fugiat, est sapiente vero ab deserunt? Voluptatum?
		Necessitatibus, excepturi eos quasi ad et, corporis molestias dignissimos totam doloremque eius iste assumenda! Repudiandae assumenda libero voluptatem, accusantium animi eveniet in deserunt atque vel vitae consectetur natus! Est, aliquid!
		Cumque amet vero delectus voluptas, dolore, consequatur iste earum cupiditate blanditiis maiores consectetur itaque? Similique, expedita, in quo maxime tempore repellendus doloremque harum quas est optio obcaecati sequi, animi minus?
		Totam dolores pariatur architecto explicabo unde magnam quos inventore vitae facilis labore libero corrupti, nostrum ea doloribus eveniet aspernatur numquam deleniti natus eius voluptate, incidunt illo laudantium tenetur. Ducimus, exercitationem.
		Fuga, sint deleniti facere praesentium alias esse natus possimus. Est cumque voluptas recusandae porro harum corporis, debitis expedita id eum accusantium neque consequuntur repellendus eveniet temporibus et ducimus voluptatem iure?
		Eveniet libero deserunt exercitationem eum. Sed libero, molestias amet minima nam quia nisi facere ea asperiores iste, aspernatur nulla reprehenderit labore veniam odit delectus vel inventore quam itaque impedit expedita.
		Rem nobis, eveniet consequuntur animi alias minima, cum adipisci impedit ex architecto tempora maxime facilis quisquam mollitia consectetur iusto quibusdam quam labore illum, provident culpa odio autem expedita optio! Necessitatibus!
		Excepturi similique cupiditate veniam! Officia dolorum amet dignissimos quam perspiciatis molestiae molestias ratione illum aut cum voluptas aliquam excepturi, provident quas odio minima veritatis! Impedit porro repudiandae corrupti neque necessitatibus.
		Libero cum voluptas dicta, non sed suscipit impedit pariatur laborum omnis nesciunt, recusandae voluptatem eos, animi quasi reprehenderit molestias qui? Iure, deserunt veritatis? Fuga ea dolores hic sit voluptates impedit.
		Laborum sint et sit reiciendis minima debitis, laboriosam, laudantium repudiandae aperiam, dolorum neque ipsa cupiditate veniam odio in accusantium id velit. Corporis, culpa? Cupiditate laboriosam illo, libero id quibusdam maxime.
		Beatae molestias quaerat quas animi eum ducimus, deleniti magni laborum reiciendis neque, consequatur nostrum vitae rem dicta non odit laboriosam aperiam, corporis impedit soluta aliquid corrupti adipisci atque blanditiis? Id.
		Distinctio eius deserunt id nulla et ratione cum quo ab nihil esse sapiente quos ex doloribus, dolores voluptate est voluptatibus laborum. Atque doloremque voluptates quas esse similique possimus saepe molestiae!
		Atque, odit ipsum! Distinctio voluptates, sit sunt quod nostrum autem soluta natus aspernatur dolorum nesciunt repellat, ullam pariatur odit exercitationem! Voluptatum molestiae possimus nam voluptates voluptas vero tenetur nobis ullam.
		Maiores molestiae, porro ab aperiam repudiandae odio quo blanditiis aut. Eius rem debitis doloribus ratione nulla provident dignissimos et pariatur repudiandae delectus repellendus nostrum aut, illo ipsam illum similique? Vitae.
		Repudiandae, in nihil fuga maiores deleniti et numquam, provident nemo vel iste sapiente unde dicta! Cupiditate expedita nihil inventore neque tempore, tempora iste ipsa, modi, doloremque quo error non reprehenderit!
		Ratione similique quae, delectus quaerat laudantium amet at deleniti labore fuga  necessitatibus velit molestias vero asperiores!
		Repellat dolore ad, saepe nisi omnis, aperiam exercitationem quae iste ipsum, autem nostrum quibusdam accusamus ab? Molestiae commodi illum reiciendis nulla doloribus repellendus in quaerat voluptate, esse odio saepe ullam?
		Consequuntur sapiente natus id alias asperiores quam minima, animi hic ullam earum ipsa rem. Deserunt minima molestias numquam et tenetur consequatur iure, repudiandae sequi ad, aut nihil dolore, fuga illum?
		</main>
	);
};

export default Main